create table
  public.allowed_users (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    email text null,
    constraint allowed_users_pkey primary key (id),
    constraint allowed_users_email_key unique (email)
  ) tablespace pg_default;