create table
  public.project (
    id uuid not null default gen_random_uuid (),
    created_at timestamp with time zone null default now(),
    about text null,
    eli5 text null,
    star_count integer null,
    issue_count integer null,
    fork_count integer null,
    pull_request_count integer null,
    contributor_count integer null,
    github_url text null,
    website_url text null,
    owning_organization uuid null,
    is_bookmarked boolean null default false,
    is_trending_daily boolean null default false,
    is_trending_weekly boolean null default false,
    is_trending_monthly boolean null default false,
    star_history array null default '{}'::json[],
    languages array null,
    owning_person uuid null,
    name text null,
    hackernews_sentiment text null,
    hackernews_stories array null,
    categories array null,
    related_twitter_posts array null,
    fork_history array null,
    languages2 array null,
    issues_per_contributor double precision null,
    forks_per_contributor double precision null,
    constraint Project_pkey primary key (id),
    constraint project_owning_organization_fkey foreign key (owning_organization) references organization (id),
    constraint project_owning_person_fkey foreign key (owning_person) references associated_person (id) on delete set null
  ) tablespace pg_default;