apiVersion: batch/v1
kind: CronJob
metadata:
  name: what-repo-cronjob
  annotations:
    "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
  labels:
    job: repo-job
spec:
  concurrency_policy: Replace
  failed_jobs_history_limit: 1
  successful_jobs_history_limit: 1
  schedule: "10 * * * *"
  jobTemplate:
    metadata:
      annotations:
        "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
      labels:
        job: repo-job
    spec:
      template:
        metadata:
          annotations:
            "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
          labels:
            job: repo-job
        spec:
          containers:
          - name: {{ .Values.resPrefix }}-repo-cronjob-container
            image: "{{.Values.image.repositoryUrl}}/repo-job:{{.Values.image.tag}}"
            envFrom:
            - configMapRef:
                name: {{ .Values.resPrefix }}-nodejs-config-map
            - configMapRef:
                name: {{ .Values.resPrefix }}-supabase-config-map
            - configMapRef:
                name: {{ .Values.resPrefix }}-repo-job-config-map
            restartPolicy: OnFailure




  
