{{- range $key, $values := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.resPrefix }}-{{ $key }}
data:
{{- range $key1, $value := $values }}
  {{$key1}}: {{$value}}
  {{- end }}
{{- end }}