apiVersion: v1
kind: Service
metadata:
  name: graphql-backend-service
spec:
  selector:
    app: {{ .Values.resPrefix }}-graphql-backend-deployment
  ports:
    - name: graphql-gateway-port
      protocol: TCP
      port: 3001
      targetPort: 3001
    - name: graphql-server-port
      protocol: TCP
      port: 3002
      targetPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resPrefix }}-ui-service
spec:
  selector:
    app: {{ .Values.resPrefix }}-ui-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000