version: "3"

silent: true


includes:
  k8s: ./config/taskfiles/Taskfile.k8s.yml
  db: ./config/taskfiles/Taskfile.db.yml
  prettier: ./config/taskfiles/Taskfile.prettier.yml
  graphql-gateway:
    taskfile: ./packages/graphql-gateway/Taskfile.yml
    dir: ./packages/graphql-gateway
    aliases:
      - "gql-gtw"
      - "gtw"
      - "g"
    vars:
      OUT: graphql-gateway
      SOURCE: ../../scripts/env/source.sh ../..
  ui:
    taskfile: ./config/taskfiles/Taskfile.npm.yml
    dir: ./packages/ui
  graphql-server:
    taskfile: ./config/taskfiles/Taskfile.go.yml
    dir: ./packages/graphql-server
    aliases:
      - "gql-srv"
      - "srv"
      - "s"
    vars:
      OUT: graphql-server
  values:
    taskfile: ./packages/build-values/Taskfile.yml
    dir: ./packages/build-values

tasks:
  init:
    desc: "Get source files to add to .zshrc/.bashrc"
    cmds:
      - echo
      - node ./scripts/init/generate.mjs
  search:
    desc: "Search for task"
    cmds:
      - echo
      - node ./scripts/task/list.mjs {{.CLI_ARGS}}
  format:
    desc: "Format files with biome"
    cmds:
      - npx biome format .
  format:fix:
    desc: "Format files with biome"
    cmds:
      - npx biome format . --write
  lint:
    desc: "Lint files with biome"
    cmds:
      - npx biome lint .
  lint:fix:
    desc: "Lint files with biome"
    cmds:
      - npx biome lint . --apply  
  biome:fix:
    desc: "Run biome check with apply"
    cmds:
      - npx biome check . --apply
  biome:ci:
    desc: "Run biome ci"
    cmds:
      - npx biome ci .
  test:
    desc: "run test for all packages"
    cmds:
      - >
        concurrently
        -n all,gql-gtw,gql-srv,ui
        -c 'green,yellow,magenta,cyan'
        'npx biome ci .' 'task gql-gtw:test' 'task gql-srv:test' 'task ui:test'
  dev:
    desc: "run dev for all packages possible"
    cmds:
      - >
        . ./scripts/env/source.sh
        &&
        concurrently
        -n gql-gateway,gql-srv,ui
        -c 'yellow,magenta,cyan'
        'task gql-gtw:dev' 'sleep 1 && task gql-srv:dev' 'task ui:dev'
  build:
    desc: "run build for all packages"
    cmds:
      - >
        . ./scripts/env/source.sh
        &&
        concurrently
        -n gql-gateway,gql-server,ui
        -c 'yellow,magenta,cyan'
        'task gql-gtw:build' 'task gql-srv:build' 'task ui:build'
  start:
    desc: "run start for all packages possible"
    cmds:
      - >
        . ./scripts/env/source.sh
        &&
        concurrently
        -n gql-gateway,gql-server,ui
        -c 'yellow,magenta,cyan'
        'task gql-gtw:start' 'sleep 1 && task gql-srv:start' 'task ui:start'
