version: '3'

env:
dotenv: ['./envs/.env', './envs/.env.local', './envs/.env.{{.ENV}}']

includes:
  k8s: 
    taskfile: ./k8s/Taskfile.yml
    dir: ./k8s
  docker: 
    taskfile: ./docker/Taskfile.yml
    dir: ./docker
  db: 
    taskfile: ./db/Taskfile.yml
    dir: ./db
  values: 
    taskfile: ./values/Taskfile.yml
    dir: ./values
  tf: ./tf/Taskfile.yml
  gateway:
    taskfile: ./packages/gateway/Taskfile.yml
    dir: ./packages/gateway
    aliases:
      - 'gtw'
      - 'g'
    vars:
      OUT: gateway # output binary
  graphql-server:
    taskfile: ./packages/graphql-server/Taskfile.yml
    dir: ./packages/graphql-server
    aliases:
      - 'gql-srv'
      - 'srv'
      - 'server'
      - 's'
    vars:
      OUT: graphql-server # output binary
  ui:
    taskfile: ./packages/ui/Taskfile.yml
    dir: ./packages/ui
    aliases:
      - 'u'
tasks:
  test:
    desc: 'run test for all packages'
    cmds:
      - >
        ./node_modules/.bin/concurrently
        -n gateway,server,ui
        -c 'yellow,magenta,cyan'
        'task g:test' 'task s:test' 'task ui:test'
  dev:
    desc: 'run dev for all packages possible'
    cmds:
      - >
        ./node_modules/.bin/concurrently
        -n gateway,server,ui
        -c 'yellow,magenta,cyan'
        'task g:dev' 'task s:dev' 'task ui:dev'
  build:
    desc: 'run build for all packages'
    cmds:
      - >
        ./node_modules/.bin/concurrently
        -n gateway,server,ui
        -c 'yellow,magenta,cyan'
        'task g:build' 'task s:build' 'task ui:build'
  start:
    desc: 'run start for all packages possible'
    cmds:
      - >
        ./node_modules/.bin/concurrently
        -n gateway,server,ui
        -c 'yellow,magenta,cyan'
        'task g:start' 'task s:start' 'task ui:start'
  install:
    desc: Install
    cmds:
      - npm install
      - cd packages/ui && npm install --legacy-peer-deps
  tag:
    desc: Create tag and push
    cmds:
      - echo "Enter tag (0.0.1)"
      - read tag && git tag -a v$tag -m "Release version v$tag" && git push origin v$tag