serve:
  endpoint: /graphql
  playground: true
  browser: false
  port: 3001
sources:
  - name: Supabase
    handler:
      graphql:
        endpoint: '{env.SUPABASE_GRAPHQL_URL}'
        operationHeaders:
          apiKey: '{env.SUPABASE_SERVICE_KEY}'
          Content-Type: application/json
          Authorization: '{context.headers["authorization"]}'
        schemaHeaders:
          apiKey: '{env.SUPABASE_SERVICE_KEY}'
          Content-Type: application/json
          Authorization: '{context.headers["authorization"]}'
  - name: Server
    handler:
      graphql:
        endpoint: '{env.GRAPHQL_SERVER_URL}'
        source: ./../graphql-server/src/graphql/schema.ts
        operationHeaders:
          Authorization: '{context.headers["authorization"]}'
        schemaHeaders:
          Authorization: '{context.headers["authorization"]}'
additionalEnvelopPlugins: './src/envelopPlugins'
