version: "3"

tasks:
  dev:
    cmds:
      - source {{.SOURCE}} && npm run dev
  dev:mesh:
    cmds:
      - source {{.SOURCE}} && npm run dev:mesh
  build:
    cmds:
      - source {{.SOURCE}} && npm run build
  build:mesh:
    cmds:
      - source {{.SOURCE}} && npm run build:mesh
  build:fastify:
    cmds:
      - source {{.SOURCE}} && npm run build:fastify
  start:
    cmds:
      - source {{.SOURCE}} && npm run start
  test:
    cmds:
      - source {{.SOURCE}} && npm run test
