version: '3'

tasks:
  dev:
    cmds:
      - source ../../scripts/env/source.sh ../.. && cargo run
  build:
    cmds:
      - source ../../scripts/env/source.sh ../.. && cargo build
  test:
    cmds:
      - cargo test && cargo check
  start:
    cmds:
      - source ../../scripts/env/source.sh ../.. && cargo run target/debug/graphql-gateway
