version: "3"
tasks:
  ### Production
  production:select:
    desc: "Publish to production cluster"
    cmds:
      - source .env.common && doctl kubernetes cluster kubeconfig save $PRODUCTION_CLUSTER
  production:publish:
    deps:
      - cluster:production
      - any:publish-production

  ### Staging
  staging:select:
    desc: "Publish to staging cluster"
    cmds:
      - source .env.common && doctl kubernetes cluster kubeconfig save $STAGING_CLUSTER

  ### Commit
  commit:select:
    desc: "Publish to commit cluster"
    cmds:
      - source .env.common && doctl kubernetes cluster kubeconfig save $COMMIT_CLUSTER

  ### Cluster
  set-cluster:
    desc: "Set current cluster"
    cmds:
      - kubectl config use-context {{.CLI_ARGS}}

  ### Any
  any:set-namespace:
    desc: "Set namespace for current cluster"
    cmds:
      - kubectl config set-context --current --namespace={{.CLI_ARGS}}
  any:ingress:ip:
    desc: "Get IP of current selected Cluster NGINX Ingress"
    cmds:
      - echo
      - ./scripts/helm/ingress/ip.mjs
  any:ingress:upgrade:
    desc: "Upgrade current NGINX Ingress"
    cmds:
      - ./scripts/helm/ingress/upgrade.mjs
  any:publish-production:
    aliases:
      - "helm-publish-production"
    desc: "Publish production cluster on any cluster"
    cmds:
      - ./scripts/helm/publish.mjs
  any:publish-subdomain:
    aliases:
      - "helm-publish-remote-env"
      - "publish-remote"
      - "remote-env"
    desc: "Publish with subdomain (environment prefix) on any cluster and sometimes with sha hash too"
    cmds:
      - ./scripts/helm/local/install.mjs
  any:uninstall-ns:commit:
    desc: "Uninstall commit namespaces on any cluster"
    cmds:
      - ./scripts/helm/app/uninstall-env.mjs commit
  any:uninstall-ns:staging:
    desc: "Uninstall staging namespaces on any cluster"
    cmds:
      - ./scripts/helm/app/uninstall-env.mjs staging
  any:uninstall-ns:production:
    desc: "Uninstall staging namespaces on any cluster"
    cmds:
      - ./scripts/helm/app/uninstall-env.mjs production
  any:uninstall-ns:
    desc: "Uninstalls namespaces for environment specified by argument on any cluster"
    cmds:
      - ./scripts/helm/app/uninstall.mjs {{.CLI_ARGS}}
