resPrefix: null
changeCause: none
hosts: []
image:
  tag: latest
  repositoryUrl: ""
configMaps:
  open-api-config-map: {}
  scraping-bot-config-map:
    SCRAPING_BOT_API_ENDPOINT: null
  graphql-server-config-map:
    GRAPHQL_SERVER_PORT: null
    GRAPHQL_SERVER_URL: null
  github-config-map:
    GITHUB_API_URL: null
  ui-config-map:
    UI_PORT: null
    NEXT_PUBLIC_GRAPHQL_URL: null
  supabase-config-map:
    SUPABASE_REFERENCE_ID: null
    SUPABASE_URL: null
    SUPABASE_GRAPHQL_URL: null
    NEXT_PUBLIC_SUPABASE_URL: null
  nodejs-config-map:
    NODE_ENV: null
    TZ: null
  golang-config-map:
    GO_ENV: null
  graphql-gateway-config-map:
    GRAPHQL_GATEWAY_PORT: null
secrets:
  ui-secret: {}
  digitalocean-secret:
    DIGITALOCEAN_ACCESS_TOKEN: null
  scraping-bot-secret:
    SCRAPING_BOT_USER_NAME: null
    SCRAPING_BOT_API_KEY: null
  graphql-gateway-secret: {}
  graphql-server-secret: {}
  supabase-secret:
    SUPABASE_ANON_KEY: null
    SUPABASE_SERVICE_KEY: null
    SUPABASE_DATABASE_URL: null
    SUPABASE_JWT_SECRET: null
  open-api-secret:
    OPENAI_API_KEY: null
  github-secret:
    GITHUB_API_TOKEN: null
