apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-backend-deployment
  annotations:
    "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
  labels:
    app: graphql-backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: graphql-backend-deployment
  template:
    metadata:
      annotations:
        "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
      labels:
        app: graphql-backend-deployment
    spec:
      automountServiceAccountToken: true
      containers:
        - name: graphql-gateway
          image: "{{ .Values.image.repositoryUrl }}/graphql-gateway:{{ default .Chart.AppVersion .Values.image.tag }}"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: nodejs-config-map
            - configMapRef:
                name: graphql-gateway-config-map
            - secretRef:
                name: graphql-gateway-secret
            - configMapRef:
                name: graphql-server-config-map
            - configMapRef:
                name: supabase-config-map
            - secretRef:
                name: supabase-secret
        - name: graphql-server
          image: "{{ .Values.image.repositoryUrl }}/graphql-server:{{ default .Chart.AppVersion .Values.image.tag }}"
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: golang-config-map
            - configMapRef:
                name: graphql-server-config-map
            - secretRef:
                name: graphql-server-secret
            - configMapRef:
                name: open-api-config-map
            - secretRef:
                name: open-api-secret
            - configMapRef:
                name: scraping-bot-config-map
            - secretRef:
                name: scraping-bot-secret
            - configMapRef:
                name: supabase-config-map
            - secretRef:
                name: supabase-secret
            - configMapRef:
                name: github-config-map
            - secretRef:
                name: github-secret         
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostIPC: false
      restartPolicy: Always