apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  annotations:
    "kubernetes.io/change-cause": "{{.Values.changeCause}}"
  labels:
    app: ui-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ui-deployment
  template:
    metadata:
      annotations:
        "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
      labels:
        app: ui-deployment
    spec:
      automountServiceAccountToken: true
      containers:
        - name: ui
          image: "{{ .Values.image.repositoryUrl }}/ui:{{ default .Chart.AppVersion .Values.image.tag }}"
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ui-config-map
            - secretRef:
                name: ui-secret
            - configMapRef:
                name: supabase-config-map
            - secretRef:
                name: supabase-secret
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostIPC: false
      restartPolicy: Always