apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    "kubernetes.io/ingress.class": nginx
spec:
  ingressClassName: nginx
  rules:
{{- range .Values.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: graphql-backend-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 3000
{{- end }}