version: '3.9'
name: truffle-ai
services:
  graphql-server:
    build:
      context: ../../
      dockerfile: ./packages/graphql_server/Dockerfile
    ports:
      - ${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}
    env_file:
      - ../../.env.production
  graphql-gateway:
    build:
      context: ../../
      dockerfile: ./packages/graphql_gateway/Dockerfile
      args:
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
        - SUPABASE_GRAPHQL_URL=${SUPABASE_GRAPHQL_URL}
        - GRAPHQL_SERVER_URL=${GRAPHQL_SERVER_URL}
    ports:
      - ${GRAPHQL_GATEWAY_PORT}:${GRAPHQL_GATEWAY_PORT}
    env_file:
      - ../../.env.production
  repo-job:
    build:
      context: ../../
      dockerfile: ./packages/repo_job/Dockerfile
    env_file:
      - ../../.env.production
  preview-job:
    build:
      context: ../../
      dockerfile: ./packages/preview_job/Dockerfile
    env_file:
      - ../../.env.production
  ui:
    build:
      context: ../../
      dockerfile: ./packages/ui/Dockerfile
    ports:
      - ${UI_PORT}:${UI_PORT}
    env_file:
      - ../../.env.production
