version: '3'

tasks:
  init:
    cmds:
      - cd workspaces/do-cluster && terraform init 
      - cd workspaces/do-dns && terraform init
      - cd workspaces/do-certificate && terraform init
  deploy:do-cluster-prod:
    cmds:
      - cd workspaces/do-cluster && terraform workspace select do-cluster-prod
      - cd workspaces/do-cluster && terraform apply -var 'cluster_name=prod-cluster'
  deploy:do-cluster-dev:
    cmds:
      - cd workspaces/do-cluster && terraform workspace select do-cluster-dev
      - cd workspaces/do-cluster && terraform apply -var 'cluster_name=dev-cluster'
  deploy:do-certificate:
    cmds:
      - cd workspaces/do-certificate && terraform apply
  deploy:do-dns-only-prod-cluster:
    cmds:
      - cd workspaces/do-dns && terraform workspace select do-dns
      - cd workspaces/do-dns && terraform apply -var 'dev_loadbalancer_name=nginx-ingress-controller-prod' -var 'prod_loadbalancer_name=nginx-ingress-controller-prod'
  deploy:do-dns-prod-and-dev-cluster:
    cmds:
      - cd workspaces/do-dns && terraform workspace select do-dns
      - cd workspaces/do-dns && terraform apply -var 'dev_loadbalancer_name=nginx-ingress-controller-dev' -var 'prod_loadbalancer_name=nginx-ingress-controller-prod'