create table
  public.founded_by (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone null default now(),
    founder_id uuid not null,
    project_id uuid not null,
    constraint founded_by_pkey primary key (id),
    constraint founded_by_founder_id_fkey foreign key (founder_id) references associated_person (id) on delete cascade,
    constraint founded_by_project_id_fkey foreign key (project_id) references project (id) on delete cascade
  ) tablespace pg_default;