version: "3"

tasks:
  merge:
    desc: "Merges all .sql files in order"
    cmds:
      - go run scripts/merge.go
  exec-merge:
    deps: [merge]
    desc: "Execute merged file"
    cmds:
      - echo $SUPABASE_DATABASE_URL
      - psql "$SUPABASE_DATABASE_URL" -f output/merged.sql
  exec-test:
    desc: "Executes .sql file in ./sql-test, expects -- <file>"
    cmds:
      - psql "$SUPABASE_DATABASE_URL" -f ./sql-test/{{.CLI_ARGS}}
  reset:
    desc: "Reset supabase database"
    cmds:
      - npx supabase db reset --db-url $SUPABASE_DATABASE_URL
      - echo "Remember this resets also Authentication"