namespace: production
SCRAPING_BOT_USER_NAME:
SCRAPING_BOT_API_KEY:
---
namespace: staging
SCRAPING_BOT_USER_NAME:
SCRAPING_BOT_API_KEY:
---
namespace: commit
SCRAPING_BOT_USER_NAME:
SCRAPING_BOT_API_KEY:
