version: '3'

tasks:
  sync:
    desc: 'Sync Svelte-Kit'
    cmds:
      - ./node_modules/.bin/svelte-kit sync
  dev:
    desc: 'Start development server on local network'
    cmds:
      - ./node_modules/.bin/vite dev --host --port $PUBLIC_UI_PORT
  build:
    desc: 'Build production'
    cmds:
      - ./node_modules/.bin/vite build
  start:
    desc: 'Preview production build locally'
    cmds:
      - ./node_modules/.bin/vite preview
  codegen-supabase:
    desc: 'Generate Supabase GraphQL codegen'
    cmds:
      - ./node_modules/.bin/graphql-codegen --config codegen.supabase.ts && sed -i '' 's/^import /&type /' src/lib/graphql/supabase/generated-codegen.ts
  schema-server:
    desc: 'Copy custom GraphQL server schema'
    cmds:
      - cp ../graphql-server/graph/schema.graphqls ./graphql-schema.server.graphql
  codegen-gateway:
    desc: 'Generate custom GraphQL gateway codegen'
    cmds:
      - ./node_modules/.bin/graphql-codegen --config codegen.gateway.ts && sed -i '' 's/^import /&type /' src/lib/graphql/gateway/generated-codegen.ts
  codegen:
    cmds:
      - task: codegen-supabase
      - task: codegen-gateway
  test:
    cmds:
      - ./node_modules/.bin/biome check
  format:
    cmds:
      - ./node_modules/.bin/biome format --write
  lint:
    cmds:
      - ./node_modules/.bin/biome lint --write
  fix:
    cmds:
      - ./node_modules/.bin/biome check --write
