version: '3'
vars:
  SOURCE: ../../scripts/env/source.sh ../..
tasks:
  dev:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/vite dev --host --port 3000
  build:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/vite build
  preview:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/vite preview
  start:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/vite start
  codegen-supabase:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/graphql-codegen --config codegen.supabase.ts && sed -i '' 's/^import /&type /' src/lib/graphql/supabase/generated-codegen.ts
  schema-server:
    cmds:
      - cp ../graphql-server/graph/schema.graphqls ./graphql-schema.server.graphql
  codegen-gateway:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/graphql-codegen --config codegen.gateway.ts
  codegen:
    cmds:
      - task: codegen-supabase
      - task: codegen-gateway
  test:
    cmds:
      - echo 'success'
