version: "3"

tasks:
  dev:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/next dev
  build:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/next build
  test:
    cmds:
      - source {{.SOURCE}} && eslint ./src
  start:
    cmds:
      - source {{.SOURCE}} && ./node_modules/.bin/next start
  codegen:
    cmds:
      - source {{.SOURCE}} && export $(cat .env.local | grep -v \"#\" | xargs) && ./node_modules/.bin/graphql-codegen --config codegen.config.ts