name: truffle-ai
services:
  graphql-server:
    container_name: graphql-server
    build:
      context: ../../packages/graphql-server
      dockerfile: ../../packages/graphql-server/Dockerfile
    ports:
      - "${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}"
    env_file:
      - ../../envs/.env
      - ../../envs/.env.commit
      - ../../envs/.env.local
  gateway:
    container_name: gateway
    build:
      context: ../../packages/gateway
      dockerfile: ../../packages/gateway/Dockerfile
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - ../../envs/.env
      - ../../envs/.env.commit
      - ../../envs/.env.local
  ui:
    container_name: ui
    build:
      context: ../../packages/ui
      dockerfile: ../../packages/ui/Dockerfile
      args:
        PUBLIC_SUPABASE_URL: ${PUBLIC_SUPABASE_URL}
        PUBLIC_SUPABASE_GRAPHQL_URL: ${PUBLIC_SUPABASE_GRAPHQL_URL}
        PUBLIC_GATEWAY_URL: ${PUBLIC_GATEWAY_URL}
        PUBLIC_UI_HOSTNAME: ${PUBLIC_UI_HOSTNAME}
        PUBLIC_UI_PORT: ${PUBLIC_UI_PORT}
        PUBLIC_SUPABASE_ANON_KEY: ${PUBLIC_SUPABASE_ANON_KEY}
    ports:
      - "${PUBLIC_UI_PORT}:${PUBLIC_UI_PORT}"
    env_file:
      - ../../envs/.env
      - ../../envs/.env.commit
      - ../../envs/.env.local
