namespace: production
SCRAPING_BOT_USER_NAME: dHlwZXNjcmlwdDIwMjMK
SCRAPING_BOT_API_KEY: ZFR1UVZpcTVSWE4yWENSb01BRnpZQnQ5MA==
---
namespace: staging
SCRAPING_BOT_USER_NAME: dHlwZXNjcmlwdDIwMjMK
SCRAPING_BOT_API_KEY: ZFR1UVZpcTVSWE4yWENSb01BRnpZQnQ5MA==
---
namespace: commit
SCRAPING_BOT_USER_NAME: dHlwZXNjcmlwdDIwMjMK
SCRAPING_BOT_API_KEY: ZFR1UVZpcTVSWE4yWENSb01BRnpZQnQ5MA==