namespace: production
NEXT_PUBLIC_SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5scGNHNW9hMjFyYkcxaWRYaHFkM3B3YVhCbklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUyT1Rjek56UTJPREFzSW1WNGNDSTZNakF4TWprMU1EWTRNSDAuQWJaZzg1SU5HQmF5UGlHcHM5LTAtdUpvcjA1U1RENHI4WkQ1X2ZSd0Zwcwo=
---
namespace: staging
NEXT_PUBLIC_SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1sdmQzSjNZMlZsZEhCNVkzaHJjSFZ4YzNOcUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUyT1Rjek9EVTVOalFzSW1WNGNDSTZNakF4TWprMk1UazJOSDAueVA4VGxCUUdxM2VlcW5odHhUN01TaWF3bXNRbE1HbnRGWFlyZ0F1aHg1awo=
---
namespace: commit
NEXT_PUBLIC_SUPABASE_ANON_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1Od1lYQnBjbVJ0ZEhwcVlXaG9ZWFptWW1GaUlpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUyT1RnMk5EazBNVFVzSW1WNGNDSTZNakF4TkRJeU5UUXhOWDAuLXJCRFNwdWstQmVaVjNSMTVfVjdES0ZEU09kbGt3ekJHbzQ5dUh0Z1EzRQo=
