{{- range $key, $values := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}
data:
{{- range $key1, $value := $values }}
  {{$key1 | quote}}: {{$value | quote}}
{{- end }}
---
{{- end }}