apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  annotations:
    "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
  labels:
    app: backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      annotations:
        "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
      labels:
        app: backend-deployment
    spec:
      automountServiceAccountToken: true
      containers:
        - name: gateway
          image: "{{ .Values.image.repositoryUrl }}/gateway:{{ default .Chart.AppVersion .Values.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: {{ .Values.GATEWAY_PORT }}
          envFrom:
            - configMapRef:
                name: golang-config-map
            - configMapRef:
                name: gateway-config-map
            - configMapRef:
                name: graphql-server-config-map
            - configMapRef:
                name: supabase-config-map
            - secretRef:
                name: supabase-secret
        - name: graphql-server
          image: "{{ .Values.image.repositoryUrl }}/graphql-server:{{ default .Chart.AppVersion .Values.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: {{ .Values.GRAPHQL_SERVER_PORT }}
          envFrom:
            - configMapRef:
                name: golang-config-map
            - configMapRef:
                name: graphql-server-config-map
            - secretRef:
                name: openai-secret
            - configMapRef:
                name: scrapingbot-config-map
            - secretRef:
                name: scrapingbot-secret
            - configMapRef:
                name: supabase-config-map
            - secretRef:
                name: supabase-secret
            - configMapRef:
                name: github-config-map
            - secretRef:
                name: github-secret      
            - secretRef:
                name: discord-secret
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostIPC: false
      restartPolicy: Always