apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  annotations:
    "kubernetes.io/change-cause": "{{.Values.changeCause}}"
  labels:
    app: frontend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      annotations:
        "kubernetes.io/change-cause": "{{ .Values.changeCause }}"
      labels:
        app: frontend-deployment
    spec:
      automountServiceAccountToken: true
      containers:
        - name: ui
          image: "{{ .Values.image.repositoryUrl }}/ui:{{ default .Chart.AppVersion .Values.image.tag }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          ports:
            - containerPort: {{ .Values.UI_PORT }}
          envFrom:
            - configMapRef:
                name: nodejs-config-map
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostIPC: false
      restartPolicy: Always