name: 'Deploy graphql-backend'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths:
      ['packages/graphql_gateway', 'packages/graphql_server', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths:
      ['packages/graphql_gateway', 'packages/graphql_server', 'config/**', '.github/workflows/**']
jobs:
  vars:
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_GRAPHQL_URL: ${{ vars.SUPABASE_GRAPHQL_URL }}
    steps:
      - run: echo "Exposing env vars"
      - run: ${{ vars.SUPABASE_GRAPHQL_URL }}
  build-graphql-gateway-image:
    needs: vars
    uses: ./.github/workflows/do-image.yml
    with:
      package_name: graphql_gateway
      build_args: --build-arg GRAPHQL_SERVER_URL=${{ vars.GRAPHQL_SERVER_URL }} --build-arg SUPABASE_URL=${{ needs.vars.outputs.SUPABASE_URL }}
    secrets:
      build_args: --build-arg SUPABASE_GRAPHQL_URL=${{needs.vars.outputs.SUPABASE_GRAPHQL_URL}} SUPABASE_SERVICE_KEY=${{ needs.vars.outputs.SUPABASE_SERVICE_KEY }}
      digital_ocean_accesstoken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  build-graphql-server-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package_name: graphql_server
    secrets:
      digital_ocean_accesstoken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  deploy-graphql-backend:
    needs: [build-graphql-gateway-image, build-graphql-server-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      templates: "['graphql-backend-deployment', 'graphql-backend-service', 'graphql-server-service']"
      template_args: >
        GRAPHQL_GATEWAY_PORT=${{vars.GRAPHQL_GATEWAY_PORT}}
        GRAPHQL_SERVER_PORT=${{vars.GRAPHQL_SERVER_PORT}}
        UI_PORT=${{vars.UI_PORT}}
        GRAPHQL_SERVER_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-graphql-server:${COMMIT_TAG}
        GRAPHQL_GATEWAY_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-graphql-gateway:${COMMIT_TAG}
    secrets:
      digital_ocean_accesstoken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
