name: 'Deploy'
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'feature/**'
    paths:
      - 'config/**'
      - 'packages/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
      - staging
    paths:
      - 'config/**'
      - 'packages/**'
      - '.github/workflows/**'
jobs:
  build:
    strategy:
      matrix:
        PACKAGE: [ui, graphql_gateway, graphql_server]
        include:
          - PACKAGE: graphql_gateway
            IMAGE: ${{vars.APP}}-graphql-gateway
            SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
            SERVER_GRAPHQL_URL: ${{ vars.SERVER_GRAPHQL_URL }}
            SUPABASE_URL: ${{ vars.SUPABASE_URL }}
          - PACKAGE: ui
            IMAGE: ${{vars.APP}}-ui
          - PACKAGE: graphql_server
            IMAGE: ${{vars.APP}}-graphql-server
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'staging' }}
    env:
      ENVIRONMENT: ${{ (github.ref == 'refs/heads/main' && 'production') || ('github.ref == 'refs/heads/staging' && 'staging') || 'commit' }}
      PREFIX: ${{ (github.ref == 'refs/heads/main' && 'production') || ('github.ref == 'refs/heads/staging' && 'staging') || (echo $GITHUB_SHA | head -c7) }}
    steps:
      - name: Checkout $GITHUB_REF
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build ${{matrix.PACKAGE}}
        if: "${{matrix.PACKAGE == 'graphql_gateway'}}"
        run: docker build --build-arg SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }} -t ${{env.ENVIRONMENT}} -t ${{vars.CONTAINER_REGISTRY_URL}}/${{matrix.IMAGE}}:$(echo $GITHUB_SHA | head -c7) -f ./packages/${{matrix.PACKAGE}}/Dockerfile .
      - name: Build ${{matrix.PACKAGE}}
        if: "${{matrix.PACKAGE != 'graphql_gateway'}}"
        run: docker build -t ${{env.ENVIRONMENT}} -t ${{vars.CONTAINER_REGISTRY_URL}}/${{matrix.IMAGE}}:$(echo $GITHUB_SHA | head -c7) -f ./packages/${{matrix.PACKAGE}}/Dockerfile .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push ${{matrix.IMAGE}} image to DigitalOcean Container Registry
        run: docker push ${{vars.CONTAINER_REGISTRY_URL}}/${{matrix.IMAGE}}:$(echo $GITHUB_SHA | head -c7)
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{vars.DO_KUBE_CLUSTER_NAME}}
      - name: Create deployment.yml from deployment.template.yml and add environment variables
        run: envsubst < $GITHUB_WORKSPACE/packages/config/deployment/deployment.template.yml > $GITHUB_WORKSPACE/.deployment/deployment.yml
      - name: Update values in deployment file
        run: >
          APP=${{vars.APP}}
          COMMIT_TAG=$(echo $GITHUB_SHA | head -c7)
          GRAPHQL_GATEWAY_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-graphql-gateway-secret --template='{{.data.PORT}}' | base64 -d)
          GRAPHQL_SERVER_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-graphql-server-secret --template='{{.data.PORT}}' | base64 -d)
          UI_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-ui-secret --template='{{.data.PORT}}' | base64 -d)
          GRAPHQL_SERVER_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-graphql-server:${COMMIT_TAG}
          GRAPHQL_GATEWAY_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-graphql-gateway:${COMMIT_TAG}
          REPO_CRONJOB_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-repo-cronjob:${COMMIT_TAG}
          UI_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-ui:${COMMIT_TAG}
          COMMIT_MESSAGE=$(echo ${{ toJSON(github.event.head_commit.message) }})
          CERTIFICATE_ID=$(doctl compute certificate list --format ID --no-header)
          ENVIRONMENT=${{ env.GITHUB_ENVIRONMENT }}
          CHANGE_CAUSE=$(echo "$COMMIT_TAG: $COMMIT_MESSAGE")
          OUTPUT_PATH=$GITHUB_WORKSPACE/.deployment/manifests
          ../../config/kubernetes/build.sh
      - name: Deploy everything
        run: kubectl apply -f $GITHUB_WORKSPACE/.deployment/manifests/deployment.yml
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-ui-deployment
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-graphql-services-deployment
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-repo-cronjob-deployment
