name: 'Deploy ui'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
jobs:
  vars:
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      NEXT_PUBLIC_API_GRAPHQL_URL: ${{ vars.NEXT_PUBLIC_API_GRAPHQL_URL }}
    steps:
      - run: echo "Exposing env vars"
  build-ui-image:
    needs: vars
    uses: ./.github/workflows/ghcr-image.yml
    with:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      package_name: ui
      build_args: --build-arg SUPABASE_URL=${{needs.vars.outputs.SUPABASE_URL}} --build-arg API_GRAPHQL_URL=${{needs.vars.outputs.NEXT_PUBLIC_API_GRAPHQL_URL}}
    secrets: inherit
