name: 'Deploy ui'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
jobs:
  build-ui-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package: ui
  deploy-ui:
    needs: [build-ui-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      template: deploy-ui
      template_args: >
        UI_PORT=${{vars.UI_PORT}}
        UI_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-ui:${COMMIT_TAG}
