name: 'Deploy GraphQL Backend'
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'feature/**'
    paths:
      - 'packages/graphql_gateway'
      - 'packages/graphql_server'
      - 'config/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
      - staging
    paths:
      - 'packages/graphql_gateway'
      - 'packages/graphql_server'
      - 'config/**'
      - '.github/workflows/**'
jobs:
  build-graphql-gateway-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package: graphql_gateway
      build_args: >
        --build-arg GRAPHQL_SERVER_URL=${{ vars.GRAPHQL_SERVER_URL }}
        --build-arg SUPABASE_URL=${{ vars.SUPABASE_URL }}
        --build-arg SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }}
  build-graphql-server-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package: graphql_server
  deploy-graphql-backend:
    needs: [build-graphql-gateway-image, build-graphql-server-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      template: deploy-graphql-backend
      template_args: >
        GRAPHQL_GATEWAY_PORT=${{vars.GRAPHQL_GATEWAY_PORT}}
        GRAPHQL_SERVER_PORT=${{vars.GRAPHQL_SERVER_PORT}}
        UI_PORT=${{vars.UI_PORT}}
        GRAPHQL_SERVER_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-graphql-server:${COMMIT_TAG}
        GRAPHQL_GATEWAY_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-graphql-gateway:${COMMIT_TAG}