name: 'Deploy preview_cronjob'
on:
  pull_request:
    types: [synchronize]
    branches: ['main', 'staging']
    paths: ['packages/preview_cronjob', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/preview_cronjob', 'config/**', '.github/workflows/**']
jobs:
  build-preview-cronjob-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package: preview_cronjob
  deploy-preview-cronjob:
    needs: [build-preview-cronjob-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      template: 'deploy-preview-cronjob'
      template_args: >
        PREVIEW_CRONJOB_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-preview-cronjob:${COMMIT_TAG}
