name: 'Deploy preview-cronjob'
on:
  pull_request:
    types: [synchronize]
    branches: ['main', 'staging']
    paths: ['packages/preview_job', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/preview_job', 'config/**', '.github/workflows/**']
jobs:
  build-preview-cronjob-image:
    uses: ./.github/workflows/ghcr-image.yml
    with:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      package_name: preview_job
    secrets: inherit
  # deploy-preview-cronjob:
  #   needs: [build-preview-cronjob-image]
  #   uses: ./.github/workflows/do-kube.yml
  #   with:
  #     delete_name: 'preview-cronjob'
  #     templates: "['preview-cronjob']"
  #     template_args: PREVIEW_CRONJOB_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}/preview-cronjob:${COMMIT_TAG}
  #   secrets: inherit
