name: 'Deploy graphql-backend'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths:
      ['packages/graphql-gateway', 'packages/graphql-server', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths:
      ['packages/graphql-gateway', 'packages/graphql-server', 'config/**', '.github/workflows/**']
jobs:
  vars:
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      GRAPHQL_SERVER_URL: ${{ vars.GRAPHQL_SERVER_URL }}
      SUPABASE_GRAPHQL_URL: ${{ vars.SUPABASE_GRAPHQL_URL }}
    steps:
      - run: echo "Exposing env vars"
  build-graphql-gateway-image:
    needs: vars
    uses: ./.github/workflows/ghcr-image.yml
    with:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      package_name: graphql_gateway
      build_args: --build-arg GRAPHQL_SERVER_URL=${{ vars.GRAPHQL_SERVER_URL }} --build-arg SUPABASE_URL=${{ needs.vars.outputs.SUPABASE_URL }} --build-arg SUPABASE_GRAPHQL_URL=${{needs.vars.outputs.SUPABASE_GRAPHQL_URL}}
    secrets: inherit
  build-graphql-server-image:
    uses: ./.github/workflows/ghcr-image.yml
    with:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      package_name: graphql_server
    secrets: inherit
