name: 'Deploy'
on:
  pull_request:
    types:
      - synchronize
    branches:
      - 'feature/**'
    paths:
      - 'packages/*_cronjob'
  push:
    branches:
      - main
      - staging
    paths:
      - 'config/**'
      - 'packages/**'
      - '.github/workflows/**'
jobs:
  build:
    strategy:
      matrix:
        PACKAGE: [deployment_preview_cronjob, repo_cronjob]
        - include:
            - PACKAGE: deployment_preview_cronjob
              IMAGE: ${{vars.APP}}-deployment-preview-cronjob
            - PACKAGE: repo_cronjob
              IMAGE: ${{vars.APP}}-repo-cronjob
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'staging' }}
    env:
      ENVIRONMENT: ${{ (github.ref == 'refs/heads/main' && 'production') || ('github.ref == 'refs/heads/staging' && 'staging') || 'commit' }}
      PREFIX: ${{ (github.ref == 'refs/heads/main' && 'production') || ('github.ref == 'refs/heads/staging' && 'staging') || (echo $GITHUB_SHA | head -c7) }}
    steps:
      - name: Checkout $GITHUB_REF
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build ${{matrix.IMAGE}} image
        run: docker build -t ${{vars.ENVIRONMENT}} -t ${{vars.CONTAINER_REGISTRY_URL}}/${{matrix.CRONJOBS}}:$(echo $GITHUB_SHA | head -c7) -f ./packages/${{matrix.PACKAGE}}/Dockerfile .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push ${{matrix.IMAGE}} image to DigitalOcean Container Registry
        run: docker push ${{vars.CONTAINER_REGISTRY_URL}}/${{matrix.IMAGE}}:$(echo $GITHUB_SHA | head -c7)
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{vars.DO_KUBE_CLUSTER_NAME}}
      - name: Create Kubernetes manifest
        run: >
          APP=${{vars.APP}}
          COMMIT_TAG=$(echo $GITHUB_SHA | head -c7)
          GRAPHQL_GATEWAY_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-graphql-gateway-secret --template='{{.data.PORT}}' | base64 -d)
          GRAPHQL_SERVER_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-graphql-server-secret --template='{{.data.PORT}}' | base64 -d)
          UI_PORT=$(kubectl get secret ${{vars.APP}}-${{ env.GITHUB_ENVIRONMENT }}-ui-secret --template='{{.data.PORT}}' | base64 -d)
          GRAPHQL_SERVER_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-graphql-server:${COMMIT_TAG}
          GRAPHQL_GATEWAY_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-graphql-gateway:${COMMIT_TAG}
          REPO_CRONJOB_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-repo-cronjob:${COMMIT_TAG}
          UI_IMAGE=registry.digitalocean.com/${{vars.APP}}-containers/${{vars.APP}}-${{ env.PREFIX }}-ui:${COMMIT_TAG}
          COMMIT_MESSAGE=$(echo ${{ toJSON(github.event.head_commit.message) }})
          CERTIFICATE_ID=$(doctl compute certificate list --format ID --no-header)
          ENVIRONMENT=${{ env.GITHUB_ENVIRONMENT }}
          CHANGE_CAUSE=$(echo "$COMMIT_TAG: $COMMIT_MESSAGE")
          OUTPUT_PATH=$GITHUB_WORKSPACE/.deployment/manifests
          ../../config/kubernetes/build.sh
      - name: Deploy everything
        run: kubectl apply -f $GITHUB_WORKSPACE/.deployment/manifests/deploy-cronjobs.yml
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-ui-deployment
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-graphql-services-deployment
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{vars.APP}-${{env.PREFIX}}-repo-cronjob-deployment
