name: 'Deploy repo-cronjob'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/repo_job', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/repo_job', 'config/**', '.github/workflows/**']
jobs:
  build-repo-cronjob-image:
    uses: ./.github/workflows/ghcr-image.yml
    with:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      package_name: repo_job
    secrets: inherit
