name: 'Deploy repo_cronjob'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/repo_cronjob', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/repo_cronjob', 'config/**', '.github/workflows/**']
jobs:
  build-repo-cronjob-image:
    uses: ./.github/workflows/do-image.yml
    with:
      package: repo_cronjob
  deploy-repo-cronjob:
    needs: [build-repo-cronjob-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      template: 'deploy-repo-cronjob'
      template_args: >
        REPO_CRONJOB_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-repo-cronjob:${COMMIT_TAG}
