name: 'Deploy ui'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/ui', 'config/**', '.github/workflows/**']
jobs:
  vars:
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      NEXT_PUBLIC_API_GRAPHQL_URL: ${{ vars.NEXT_PUBLIC_API_GRAPHQL_URL }}
    steps:
      - run: echo "Exposing env vars"
  build-ui-image:
    needs: vars
    uses: ./.github/workflows/do-image.yml
    with:
      package_name: ui
      build_args: --build-arg NEXT_PUBLIC_SUPABASE_URL=${{needs.vars.outputs.SUPABASE_URL}} --build-arg NEXT_PUBLIC_API_GRAPHQL_URL=${{needs.vars.outputs.NEXT_PUBLIC_API_GRAPHQL_URL}}
    secrets:
      digital_ocean_accesstoken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  deploy-ui:
    needs: [build-ui-image]
    uses: ./.github/workflows/do-kube.yml
    with:
      templates: "['ui-deployment', 'ui-service']"
      template_args: >
        UI_PORT=${{vars.UI_PORT}}
        UI_IMAGE=${{vars.CONTAINER_REGISTRY_URL}}/${{vars.APP}}-${ENVIRONMENT}-ui:${COMMIT_TAG}
    secrets:
      digital_ocean_accesstoken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
