name: 'DO-Init'
description: 'Checkout repo and install doctl'
runs:
  environment: ${{ startsWith(github.ref_name, 'feature/') && 'commit' || github.ref_name }}
  using: "composite"
  steps:
    - name: Checkout $GITHUB_REF
      uses: actions/checkout@v4
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.digitalocean_access_token }}