name: 'DO kube'
on:
  workflow_call:
    inputs:
      template:
        type: string
        required: true
      template_args:
        type: string
        required: true
      delete_name:
        type: string
        required: false
    secrets:
      digital_ocean_accesstoken:
        required: true
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    env:
      environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    steps:
      - name: Checkout $GITHUB_REF
        uses: actions/checkout@v4
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.digital_ocean_accesstoken }}
      # - uses: ./.github/workflows/do-init.yml
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{vars.DO_KUBE_CLUSTER_NAME}}
      - name: Delete
        if: inputs.delete_name
        run: kubectl delete pod --namespace=${{ env.environment }} -l name=${{inputs.delete_name}}
      - name: Build manifest
        run: >
          APP=${{vars.APP}}
          COMMIT_TAG=$(echo $GITHUB_SHA | head -c7)
          COMMIT_MESSAGE=$(echo ${{ toJSON(github.event.head_commit.message) }})
          CHANGE_CAUSE=$(echo "$COMMIT_TAG: $COMMIT_MESSAGE")
          PREFIX="${{env.environment}}${{(env.environment == 'commit' && '-$COMMIT_TAG') || ''}}"
          ENVIRONMENT=${{ env.environment }}
          NAMESPACE=${{ env.environment }}
          ${{inputs.template_args}} $GITHUB_WORKSPACE/config/kubernetes/build-single.sh $GITHUB_WORKSPACE/config/kubernetes/${{inputs.template}}.yml ${{inputs.template}}.yml
      - name: Deploy manifest
        run: kubectl apply -f $GITHUB_WORKSPACE/.deployment/${{inputs.template}}.yml
      - name: Verify deployment
        run: kubectl rollout status --timeout 240s deployment/${{inputs.template}}
      - name: Build ingress manifest
        run: >
          APP=${{vars.APP}}
          COMMIT_TAG=$(echo $GITHUB_SHA | head -c7)
          COMMIT_MESSAGE=$(echo ${{ toJSON(github.event.head_commit.message) }})
          CHANGE_CAUSE=$(echo "$COMMIT_TAG: $COMMIT_MESSAGE")
          PREFIX="${{env.environment}}$((env.environment = 'commit' ? '-$COMMIT_TAG' : ''))"
          ENVIRONMENT=${{ env.environment }}
          NAMESPACE=${{ env.environment }}
          $GITHUB_WORKSPACE/config/kubernetes/build-single.sh $GITHUB_WORKSPACE/config/kubernetes/deploy-ingress.yml deploy-ingress.yml
      - name: Deploy ingress manifest
        run: kubectl apply -f $GITHUB_WORKSPACE/.deployment/deploy-ingress.yml
      - name: Verify ingress deployment
        run: >
          PREFIX="${{env.environment}}$((env.environment = 'commit' ? '-$COMMIT_TAG' : ''))"
          kubectl rollout status --timeout 240s ingress/${{vars.APP}}-$(echo $PREFIX)-virtual-host-ingress
