name: Helm
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF: ${{ github.ref }}
      REF_NAME: ${{ github.ref_name }}
    secrets: inherit
  package-helm:
    name: Helm
    needs: variables
    runs-on: ubuntu-latest
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2
      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.7.0
      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{vars.ORG_NAME}}/${{vars.RELEASE_REPO_NAME}}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          path: helm-chart-repository
      - name: Helm Package
        run: helm package config/app-chart --version "0.1.0+$("${{ needs.variables.outputs.GIT_COMMIT_TAG }}" | head -c 7)" -d helm-chart-repository
      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        run: |
          git config --global user.email "bot@truffle.tools"
          git config --global user.name "TruffleAI Bot"
          CHART_PACKAGE_NAME="app-chart-0.1.0+$("${{ needs.variables.outputs.GIT_COMMIT_TAG }}" | head -c 7).tgz"
          cd helm-chart-repository
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main