name: Images
on:
  pull_request:
    types:
      - synchronize
      - opened
    branches: ['staging']
    paths: ['packages/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', '.github/workflows/**']
permissions:
  contents: read
  packages: write
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
    secrets: inherit
  image:
    environment: ${{needs.variables.outputs.ENV}}
    name: 'Image'
    permissions:
      contents: read
      packages: write
    needs: variables
    strategy:
      matrix:
        PACKAGE_NAME: [ui, auth-server, graphql-server]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: |
              --build-arg PUBLIC_SUPABASE_URL="${{vars.PUBLIC_SUPABASE_URL}}"
              --build-arg PUBLIC_SUPABASE_GRAPHQL_URL="${{vars.PUBLIC_SUPABASE_GRAPHQL_URL}}"
              --build-arg PUBLIC_GATEWAY_URL="${{vars.PUBLIC_GATEWAY_URL}}"
              --build-arg PUBLIC_UI_HOSTNAME="${{vars.PUBLIC_UI_HOSTNAME}}"
              --build-arg PUBLIC_UI_PORT="${{vars.PUBLIC_UI_PORT}}"
              --build-arg PUBLIC_SUPABASE_ANON_KEY="${{secrets.PUBLIC_SUPABASE_ANON_KEY}}"
    uses: ./.github/workflows/reusable-ghcr-image.yml
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      ENV: ${{needs.variables.outputs.ENV}}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      BUILD_ARGS: ${{matrix.BUILD_ARGS}}
      IMAGE_REPOSITORY: dev
      IMAGE_TAGS: >-
        dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        ${{needs.variables.outputs.DATETIME}}
        latest
    secrets: inherit
