name: Images
on:
  pull_request:
    types:
      - synchronize
      - opened
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF_NAME: ${{ github.ref_name }}
    secrets: inherit
  image:
    name: 'Image'
    permissions:
      contents: read
      packages: write
    needs: variables
    strategy:
      matrix:
        PACKAGE_NAME: [ui, graphql-gateway, graphql-server, repo-job]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: --build-arg SUPABASE_URL="${{needs.variables.outputs.SUPABASE_URL}}" --build-arg GRAPHQL_URL="${{needs.variables.outputs.GRAPHQL_URL}}"
          - PACKAGE_NAME: graphql-gateway
            BUILD_ARGS: --build-arg GRAPHQL_SERVER_URL="${{ needs.variables.outputs.GRAPHQL_SERVER_URL }}" --build-arg SUPABASE_URL="${{ needs.variables.outputs.SUPABASE_URL }}" --build-arg SUPABASE_GRAPHQL_URL="${{needs.variables.outputs.SUPABASE_GRAPHQL_URL}}"
    uses: ./.github/workflows/reusable-ghcr-image.yml
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      ENVIRONMENT: ${{needs.variables.outputs.ENVIRONMENT}}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      IMAGE_REPOSITORY: dev
      ARGS: >-
        ${{matrix.BUILD_ARGS}}
        -t ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        -t ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG_N7}}
        -t ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG_N14}}
        -t dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        -t dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        -t 0.0.1-dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        -t 0.0.1-dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        -t ${{needs.variables.outputs.ENVIRONMENT}}-latest
        -t ${{needs.variables.outputs.DATETIME}}
    secrets: inherit
