name: Images
on:
  pull_request:
    types:
      - synchronize
      - opened
    branches: ['staging']
    paths: ['packages/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', '.github/workflows/**']
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
    secrets: inherit
  image:
    name: 'Image'
    uses: ./.github/workflows/reusable-ghcr-image.yml
    needs: variables
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        PACKAGE_NAME: [ui, gateway, graphql-server]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: >
              --build-arg PUBLIC_SUPABASE_URL="${{needs.variables.outputs.PUBLIC_SUPABASE_URL}}"
              --build-arg PUBLIC_SUPABASE_GRAPHQL_URL="${{needs.variables.outputs.PUBLIC_SUPABASE_GRAPHQL_URL}}"
              --build-arg PUBLIC_GATEWAY_URL="${{needs.variables.outputs.PUBLIC_GATEWAY_URL}}"
              --build-arg PUBLIC_UI_HOSTNAME="${{needs.variables.outputs.PUBLIC_UI_HOSTNAME}}"
              --build-arg PUBLIC_UI_PORT="${{needs.variables.outputs.PUBLIC_UI_PORT}}"
              --build-arg PUBLIC_SUPABASE_ANON_KEY="${{needs.variables.outputs.PUBLIC_SUPABASE_ANON_KEY}}"
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      ENV: ${{ needs.variables.outputs.ENV }}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      BUILD_ARGS: ${{matrix.BUILD_ARGS}}
      IMAGE_REPOSITORY: dev
      IMAGE_TAGS: >-
        dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        ${{needs.variables.outputs.DATETIME}}
        latest
    secrets: inherit
