name: Images
on:
  pull_request:
    types:
      - synchronize
      - opened
    branches: ['staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
    secrets: inherit
  image:
    name: 'Image'
    permissions:
      contents: read
      packages: write
    needs: variables
    strategy:
      matrix:
        PACKAGE_NAME: [ui, graphql-gateway, graphql-server]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: --build-arg SUPABASE_URL="${{needs.variables.outputs.SUPABASE_URL}}" --build-arg SUPABASE_GRAPHQL_URL="${{needs.variables.outputs.SUPABASE_GRAPHQL_URL}}" --build-arg GATEWAY_GRAPHQL_URL="${{needs.variables.outputs.GATEWAY_GRAPHQL_URL}}" --build-arg UI_HOSTNAME="${{needs.variables.outputs.UI_HOSTNAME}}" --build-arg UI_PORT="${{needs.variables.outputs.UI_PORT}}"
          - PACKAGE_NAME: graphql-gateway
            BUILD_ARGS: --build-arg GRAPHQL_SERVER_URL="${{ needs.variables.outputs.GRAPHQL_SERVER_URL }}" --build-arg SUPABASE_URL="${{ needs.variables.outputs.SUPABASE_URL }}" --build-arg SUPABASE_GRAPHQL_URL="${{needs.variables.outputs.SUPABASE_GRAPHQL_URL}}"
    uses: ./.github/workflows/reusable-ghcr-image.yml
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      ENVIRONMENT: ${{needs.variables.outputs.ENVIRONMENT}}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      BUILD_ARGS: ${{matrix.BUILD_ARGS}}
      IMAGE_REPOSITORY: dev
      IMAGE_TAGS: >-
        ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG_N7}}
        ${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG_N14}}
        ${{needs.variables.outputs.ENVIRONMENT}}-latest
        dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        0.0.1-dev-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        0.0.1-dev-${{needs.variables.outputs.ENVIRONMENT}}-${{needs.variables.outputs.GIT_COMMIT_TAG}}
        ${{needs.variables.outputs.ENVIRONMENT}}-latest
        ${{needs.variables.outputs.DATETIME}}
        latest
    secrets: inherit
