name: 'Plan Deployment'
on:
  pull_request:
    types:
      - synchronize
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
  push:
    branches: ['main', 'staging']
    paths: ['packages/**', 'config/**', '.github/workflows/**']
jobs:
  variables:
    name: 'Variables'
    environment: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
      GRAPHQL_SERVER_URL: ${{ vars.GRAPHQL_SERVER_URL }}
      SUPABASE_GRAPHQL_URL: ${{ vars.SUPABASE_GRAPHQL_URL }}
      NEXT_PUBLIC_API_GRAPHQL_URL: ${{ vars.NEXT_PUBLIC_API_GRAPHQL_URL }}
      GIT_COMMIT_TAG: ${{ steps.git_commit_tag.outputs.git_commit_tag }}
      GIT_COMMIT_MESSAGE: ${{ steps.git_commit_message.outputs.git_commit_message }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.sha}}
          sparse-checkout: |
            .git
      - id: git_commit_tag
        run: if [[ -n "${{github.event.pull_request.head.sha}})" ]]; then echo "git_commit_tag=$(echo '${{github.event.pull_request.head.sha}}' | head -c7)" >> "$GITHUB_OUTPUT"; else echo "git_commit_tag=${{github.sha}}" >> "$GITHUB_OUTPUT"; fi
      - id: git_commit_message
        run: if [[ -n "$(git log --format=%s -n 1 ${{github.event.pull_request.head.sha}})" ]]; then echo "git_commit_message=$(git log --format=%s -n 1 ${{github.event.pull_request.head.sha}})" >> "$GITHUB_OUTPUT"; else echo "git_commit_message=${{github.event.head_commit.message}}" >> "$GITHUB_OUTPUT"; fi

  image:
    name: 'Image'
    permissions:
      contents: read
      packages: write
    needs: variables
    strategy:
      matrix:
        PACKAGE_NAME: [ui, graphql-gateway, graphql-server, repo-job, preview-job]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: --build-arg SUPABASE_URL=${{needs.variables.outputs.SUPABASE_URL}} --build-arg API_GRAPHQL_URL=${{needs.variables.outputs.NEXT_PUBLIC_API_GRAPHQL_URL}}
          - PACKAGE_NAME: graphql-gateway
            BUILD_ARGS: --build-arg GRAPHQL_SERVER_URL=${{ needs.variables.outputs.GRAPHQL_SERVER_URL }} --build-arg SUPABASE_URL=${{ needs.variables.outputs.SUPABASE_URL }} --build-arg SUPABASE_GRAPHQL_URL=${{needs.variables.outputs.SUPABASE_GRAPHQL_URL}}
    uses: ./.github/workflows/reusable-ghcr-image.yml
    with:
      ENVIRONMENT: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      BUILD_ARGS: ${{matrix.BUILD_ARGS}}
    secrets: inherit
  terraform-plan:
    name: 'Terraform Plan'
    permissions:
      contents: read
      pull-requests: write
    needs: [variables, image]
    uses: ./.github/workflows/reusable-terraform-plan.yml
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      GIT_COMMIT_MESSAGE: ${{needs.variables.outputs.GIT_COMMIT_MESSAGE}}
      ENVIRONMENT: ${{ startsWith(github.ref, 'refs/pull') && 'commit' || github.ref_name }}
    secrets: inherit
