name: Release
on:
  push:
    tags: ['v*.*.*']
jobs:
  variables:
    name: Variables
    uses: ./.github/workflows/reusable-variables.yml
    with:
      REF_NAME: ${{ github.ref_name }}
    secrets: inherit
  release_tag:
    name: Get release tag
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TAG: ${{steps.tag.outputs.RELEASE_TAG}}
    steps:
      - id: tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_OUTPUT
  image:
    name: 'Image'
    permissions:
      contents: read
      packages: write
    needs: [variables, release_tag]
    strategy:
      matrix:
        PACKAGE_NAME: [ui, graphql-gateway, graphql-server, repo-job]
        include:
          - PACKAGE_NAME: ui
            BUILD_ARGS: --build-arg SUPABASE_URL="${{needs.variables.outputs.SUPABASE_URL}}" --build-arg GRAPHQL_URL="${{needs.variables.outputs.GRAPHQL_URL}}"
          - PACKAGE_NAME: graphql-gateway
            BUILD_ARGS: --build-arg GRAPHQL_SERVER_URL="${{ needs.variables.outputs.GRAPHQL_SERVER_URL }}" --build-arg SUPABASE_URL="${{ needs.variables.outputs.SUPABASE_URL }}" --build-arg SUPABASE_GRAPHQL_URL="${{needs.variables.outputs.SUPABASE_GRAPHQL_URL}}"
    uses: ./.github/workflows/reusable-ghcr-image.yml
    with:
      GIT_COMMIT_TAG: ${{needs.variables.outputs.GIT_COMMIT_TAG}}
      ENVIRONMENT: ${{needs.variables.outputs.ENVIRONMENT}}
      PACKAGE_NAME: ${{matrix.PACKAGE_NAME}}
      BUILD_ARGS: ${{matrix.BUILD_ARGS}}
      IMAGE_REPOSITORY: stable
      IMAGE_TAGS: >-
        ${{needs.release_tag.outputs.RELEASE_TAG}}
        latest
    secrets: inherit
  helm:
    name: Helm
    needs: [variables, release_tag]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout chart
        uses: actions/checkout@v2
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Helm Package App
        run: helm package config/charts/app-chart --version ${{needs.release_tag.outputs.RELEASE_TAG}} --app-version ${{needs.release_tag.outputs.RELEASE_TAG}}
      - name: Login Helm
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Push Helm
        run: helm push app-chart-${{needs.release_tag.outputs.RELEASE_TAG}}.tgz oci://ghcr.io/${{vars.ORG_NAME}}/${{vars.REPO_NAME}}/stable
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: image
    steps:
      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create
        uses: 'actions/github-script@v7'
        with:
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                body: "## Packages\n[Packages](https://github.com/orgs/${{vars.ORG_NAME}}/packages) see all stable releases",
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: true,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });
              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
