name: 'DO image'
on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
      GIT_COMMIT_TAG:
        type: string
        required: true
      BUILD_ARGS:
        type: string
        required: false
      IMAGE_DESCRIPTION:
        type: string
        required: false
      ENVIRONMENT:
        type: string
        required: true
      IMAGE_REPOSITORY:
        type: string
        required: true
      IMAGE_TAGS:
        type: string
        required: true
permissions:
  contents: read
  packages: write
jobs:
  ghcr-image:
    name: 'GitHub Container Registry'
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    env:
      CONTAINER_REGISTRY_DOMAIN: ghcr.io
      IMAGE_SOURCE: https://github.com/${{vars.ORG_NAME}}/${{vars.REPO_NAME}}
      IMAGE_LICENSE: MIT
      IMAGE_DESCRIPTION: ${{ inputs.IMAGE_DESCRIPTION || inputs.PACKAGE_NAME}}
      IMAGE_MAIN_REPOSITORY_URL: ghcr.io/${{vars.ORG_NAME}}/${{vars.REPO_NAME}}
    steps:
      - name: Checkout $GITHUB_REF
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.CONTAINER_REGISTRY_DOMAIN }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
           DOCKER_BUILDKIT=1 docker build \
          ${{inputs.ARGS}} \
          --build-arg SUPABASE_ANON_KEY=${{secrets.SUPABASE_ANON_KEY}} \
          --build-arg SUPABASE_SERVICE_KEY=${{ secrets.SUPABASE_SERVICE_KEY }} \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          -t ${{env.IMAGE_REPOSITORY_URL}}/${{inputs.PACKAGE_NAME}}:${{inputs.GIT_COMMIT_TAG}} \
          -t ${{env.IMAGE_REPOSITORY_URL}}/${{inputs.PACKAGE_NAME}}:${{inputs.ENVIRONMENT}}-${{inputs.GIT_COMMIT_TAG}} \
          -t ${{env.IMAGE_REPOSITORY_URL}}/${{inputs.PACKAGE_NAME}}:latest \
          -t ${{env.IMAGE_REPOSITORY_URL}}/${{inputs.PACKAGE_NAME}}:${{inputs.ENVIRONMENT}}-latest \
          --label "org.opencontainers.image.source=${{env.IMAGE_SOURCE}}" \
          --label "org.opencontainers.image.description=${{env.IMAGE_DESCRIPTION}}" \
          --label "org.opencontainers.image.licenses=${{env.IMAGE_LICENSE}}" \
          -f ./packages/${{inputs.PACKAGE_NAME}}/Dockerfile .
      - name: Push image to ghcr
        run: docker push --all-tags ${{env.IMAGE_MAIN_REPOSITORY_URL}}/${{inputs.IMAGE_REPOSITORY}}/${{inputs.PACKAGE_NAME}}
#   docker build \
#   -f ./packages/graphql-server/Dockerfile . \
#   --build-arg SUPABASE_ANON_KEY=*** \
#   --build-arg SUPABASE_SERVICE_KEY=*** \
#   --build-arg BUILDKIT_INLINE_CACHE=1 \
# "${args[@]}" \
#   -t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:$(echo "0fa10022f20097bdf70f876f862d1f00eac54691" | head -c 7) \
#   -t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:$(echo "0fa10022f20097bdf70f876f862d1f00eac54691" | head -c 14) \
#   -t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:0fa10022f20097bdf70f876f862d1f00eac54691 \
#   -t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:latest \
#   --label "org.opencontainers.image.source=https://github.com/viets-software-club/truffle-ai" \
#   --label "org.opencontainers.image.description=graphql-server" \
#   --label "org.opencontainers.image.licenses=MIT"
  

        # 
        # declare -a args=();
        # for tag in "commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit- commit- dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit-latest"; do args+=("-t") args+=("ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:$tag"); done;

        # docker build . $(for tag in $(printf "commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit- commit- dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit-latest "); do echo -n "-t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:$tag"; done;)

        # declare -a  args=()
        # for tag in $(printf "commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit- commit- dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-c5c3a9ea660ec67b31a161524dcc1d7206569840 0.0.1-dev-commit-c5c3a9ea660ec67b31a161524dcc1d7206569840 commit-latest"); do args+="-t ghcr.io/viets-software-club/truffle-ai/dev/graphql-server:$tag "; done;
        # "${args[@]}"


          #    declare -a args=(
          #   "--build-arg"
          #   "SUPABASE_ANON_KEY=wow"
          #   "--build-arg"
          #   "SUPABASE_SERVICE_KEY=wow"
          #   "--build-arg"
          #   "BUILDKIT_INLINE_CACHE=1"
          #   "-t"
          #   "wow/wow/wow:$(echo "wow" | head -c 7)"
          #   "-t"
          #   "wow/wiw/wow:latest"
          #   "--label"
          #   "org.opencontainers.image.source=wow"
          #   "--label"
          #   "org.opencontainers.image.description=wow"
          #   "--label"
          #   "org.opencontainers.image.licenses=wow"
          #   "-f"
          #   "/packages/wow/Dockerfile"
          # );
          # args+="hey"
          

  #          declare -a args=(
  #   "--build-arg"
  #   "SUPABASE_ANON_KEY=***"
  #   "--build-arg"
  #   "SUPABASE_SERVICE_KEY=***"
  #   "--build-arg"
  #   "BUILDKIT_INLINE_CACHE=1"
  #   "-t"
  #   "ghcr.io/viets-software-club/truffle-ai/dev/repo-job:$(echo "d932ff876804c1bc24f317af128820951410fca7" | head -c 7)"
  #   "-t"
  #   "ghcr.io/viets-software-club/truffle-ai/dev/repo-job:$(echo "d932ff876804c1bc24f317af128820951410fca7" | head -c 14)"
  #   "-t"
  #   "ghcr.io/viets-software-club/truffle-ai/dev/repo-job:d932ff876804c1bc24f317af128820951410fca7"
  #   "-t"
  #   "ghcr.io/viets-software-club/truffle-ai/dev/repo-job:latest"
  #   "--label"
  #   "org.opencontainers.image.source=https://github.com/viets-software-club/truffle-ai"
  #   "--label"
  #   "org.opencontainers.image.description=repo-job"
  #   "--label"
  #   "org.opencontainers.image.licenses=MIT"
  #   "-f"
  #   "/packages/repo-job/Dockerfile"
  # );
  # str="commit-d932ff876804c1bc24f317af128820951410fca7 commit- commit- dev-d932ff876804c1bc24f317af128820951410fca7 dev-commit-d932ff876804c1bc24f317af128820951410fca7 0.0.1-dev-d932ff876804c1bc24f317af128820951410fca7 0.0.1-dev-commit-d932ff876804c1bc24f317af128820951410fca7 commit-latest"
  # for tag in ${str}; do args+=("-t"); args+=("ghcr.io/viets-software-club/truffle-ai/dev/repo-job:$tag"); done;
  # DOCKER_BUILDKIT=1 docker build "${args[@]}" .